# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-12 04:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190311_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 12, 4, 57, 35, 777949, tzinfo=utc)),
        ),
    ]
