# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-12 05:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190311_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 12, 5, 58, 21, 125210, tzinfo=utc)),
        ),
    ]
