# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-12 06:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190311_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 12, 6, 18, 29, 68371, tzinfo=utc)),
        ),
    ]
